version: '2' 
services: 
  # client:
  #   container_name: auc-client
  #   build:
  #     context: ./client
  #     args:
  #       - SERVER_URL=http://localhost:8481/
  #   ports:
  #     - "80:80"
  db:
    container_name: auc-db
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: 2
      MYSQL_DATABASE: auction_demo_scheduler
  server:
    container_name: auc-server
    build:
      context: ./server
    depends_on:
      db:
        condition: service_started
