version: '2' 
services: 
   nginx: 
      image: "nginx:latest" 
      restart: always 
      ports: 
      - 80:80 
      volumes: 
      - "./configuration/nginx/conf.d:/etc/nginx/conf.d/default.conf" 
      - "./client/build/web:/var/www/html" 

