version: '2' 
services: 
  db:
    container_name: auc-db
    build:
      context: ./db
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 2
      MYSQL_DATABASE: auction_demo_scheduler
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - local
  server:
    container_name: auc-server
    build:
      context: ./server
      args:
        - DATASOURCE_URL=jdbc:mysql://auc-db:3306/auction_demo
        - DATASOURCE_PASSWORD=2
        - QRTZ_DATASOURCE_URL=jdbc:mysql://auc-db:3306/auction_demo_scheduler
        - QRTZ_DATASOURCE_PASSWORD=2
        - MESSAGING_URL=http://auc-centrifugo:8000/api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8481:8481"
    networks:
      - local
  client:
    container_name: auc-client
    build:
      context: ./client
      args:
        - SERVER_URL=http://158.160.73.90:8481/
        - MESSAGING_URL=http://158.160.73.90:8000/
    ports:
      - "80:80"
    networks:
      - local
  centrifugo:
    container_name: auc-centrifugo
    image: centrifugo/centrifugo:v4
    volumes:
      - ./centrifuge/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - "8000:8000"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - local


networks:
  local:
    driver: bridge
