version: '2' 
services: 
  client:
    container_name: auc-client
    build:
      context: ./client
      args:
        - SERVER_URL=http://auc-server:8481/
    ports:
      - "80:80"
  db:
    container_name: auc-db
    build:
      context: ./db
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 2
      MYSQL_DATABASE: auction_demo_scheduler
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - local
  server:
    container_name: auc-server
    build:
      context: ./server
      args:
        - DATASOURCE_URL=jdbc:mysql://auc-db:3306/auction_demo
        - DATASOURCE_PASSWORD=2
        - QRTZ_DATASOURCE_URL=jdbc:mysql://auc-db:3306/auction_demo_scheduler
        - QRTZ_DATASOURCE_PASSWORD=2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8481"
    networks:
      - local


networks:
  local:
    driver: bridge
