version: '2' 
services: 
  # client:
  #   container_name: auc-client
  #   build:
  #     context: ./client
  #     args:
  #       - SERVER_URL=http://localhost:8481/
  #   ports:
  #     - "80:80"
  db:
    build:
      context: ./db
    volumes:
      - .:docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 2
      MYSQL_DATABASE: auction_demo_scheduler
    # command: ["bash", "-c", "/setupdb.sh && tail -f /dev/null"]
    # entrypoint: ["mysqld --initialize", "mysqld"]
