version: '2' 
services: 
  # client:
  #   container_name: auc-client
  #   build:
  #     context: ./client
  #     args:
  #       - SERVER_URL=http://localhost:8481/
  #   ports:
  #     - "80:80"
  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: 2
    command: ["bash", "-c", "/setupdb.sh"]
    entrypoint: ["mysqld"]
